zeppelin:
  image: dylanmei/zeppelin:0.6.0-stable
  environment:
    ZEPPELIN_PORT: 8080
    ZEPPELIN_JAVA_OPTS: >-
      -Dspark.driver.memory=1g
      -Dspark.executor.memory=1g
    MASTER: local[*]
  ports:
    - 8090:8080
  volumes:
    - ./data:/usr/zeppelin/data
    - ./notebooks:/usr/zeppelin/notebook
